// [3.9.1]
// Imports centralized house interaction data.
import { houseZones } from "../data/houseZones.js";

// [3.9.2]
// Imports centralized application state.
import { energyState } from "../core/energyState.js";

// =====================================================
// [18.9.1]
// Imports centralized building presentation state.
//
// This provides contextual building intelligence that has
// already been resolved by the presentation service.
// The interaction engine consumes that intelligence but
// does not calculate it.
// =====================================================

import {
    buildingPresentationState
} from "../core/buildingPresentationState.js";

// [3.9.4]
// Imports SVG visualization renderer.
import {
    renderInstalledSystems
} from "./visualSystemRenderer.js";


//after system selection panel
import { openSystemSelectionPanel } from "./systemSelectionPanel.js";

// [6.4.13]
// Imports persistence synchronization layer.
import {
    saveEngineeringState
} from "../services/persistenceService.js";

import {

    supportsHover,

    isTouchDevice,

    isMobileViewport,

    getDeviceProfile

}

from "../utils/deviceDetector.js";


// [3.9.5]
// Initializes scalable SVG interaction engine.
export function initializeHouseInteractions() {

// =====================================================
// [14.1.6]
// Detects the current interaction profile.
// =====================================================

const device = getDeviceProfile();

console.log(
    "Interaction Profile:",
    device
);

console.log(
    "Supports Hover:",
    supportsHover()
);

console.log(
    "Touch Device:",
    isTouchDevice()
);

console.log(
    "Mobile Viewport:",
    isMobileViewport()
);

    // [3.9.6]
    // Retrieves all interactive SVG zones.
    const interactiveZones =
        document.querySelectorAll(
            ".interactive-zone"
        );

    // [3.9.7]
    // Retrieves tooltip container.
    const tooltip =
        document.getElementById(
            "house-tooltip"
        );

// =====================================================
// [15.1.6]
// Retrieves touch guidance.
// =====================================================

const touchGuidance =
    document.getElementById(
        "touch-guidance"
    );


    // =====================================================
// [18.9.2]
// Retrieves the resolved building presentation.
//
// The presentation service has already determined which
// building components are available, which are currently
// represented by the SVG, and which remain future
// presentation opportunities.
// =====================================================

const buildingPresentation =
    buildingPresentationState.presentation;

    

    // =====================================================
// [15.1.7]
// Initializes first-use touch guidance.
// =====================================================

if (
    touchGuidance &&
    (
        isTouchDevice() ||
        isMobileViewport()
    )
) {

    touchGuidance.classList.remove(
        "hidden"
    );

}

    // [3.9.8]
    // Iterates through all interactive zones.
    interactiveZones.forEach(zone => {

        // [3.9.9]
        // Retrieves scalable zone identifier.
        const zoneKey =
            zone.dataset.zone;

        // [3.9.10]
        // Retrieves scalable zone metadata.
        const zoneData =
            houseZones[zoneKey];

        // ================================
        // HOVER INTERACTION
        // ================================

        // [3.9.11]
        // Activates hover interaction behavior.
        zone.addEventListener(
            "mouseenter",
            () => {

                // [3.9.12]
                // Updates tooltip dynamically.
// =====================================================
// [18.9.3]
// Resolves contextual presentation data for the active zone.
//
// The interaction engine consumes presentation intelligence
// generated by the domain and presentation layers rather
// than hard-coding heat-loss knowledge here.
// =====================================================

const presentationZone =
    buildingPresentation?.zones?.find(
        zone =>
            zone.id === zoneKey
    );

// =====================================================
// [18.9.4]
// Builds contextual tooltip content safely.
//
// The existing static house-zone metadata remains the
// fallback so the SVG interaction system remains resilient
// if presentation state has not yet been initialized.
// =====================================================

const contextualTitle =
    presentationZone?.name ??
    zoneData.title;

const contextualDescription =
    presentationZone?.description ??
    zoneData.description;

// =====================================================
// [18.9.5]
// Builds the renovation opportunity summary.
//
// Heat-loss percentages and renovation opportunities are
// supplied by the presentation layer rather than calculated
// inside the interaction engine.
// =====================================================

const heatLossShare =
    presentationZone?.heatLossShare;

const renovationOpportunities =
    presentationZone?.renovationOpportunities ??
    [];

// =====================================================
// [18.9.6]
// Renders contextual building information.
//
// textContent is used for user-controlled/domain-derived
// text rather than injecting raw HTML content.
// =====================================================

tooltip.innerHTML = "";

const titleElement =
    document.createElement("h3");

titleElement.textContent =
    contextualTitle;

tooltip.appendChild(
    titleElement
);

const descriptionElement =
    document.createElement("p");

descriptionElement.textContent =
    contextualDescription;

tooltip.appendChild(
    descriptionElement
);

// =====================================================
// [18.9.7]
// Displays modeled heat-loss opportunity when available.
//
// The value represents the modeled share defined by the
// building heat-loss domain data. It is not presented as a
// universal physical loss percentage for every building.
// =====================================================

if (
    typeof heatLossShare === "number"
) {

    const heatLossElement =
        document.createElement("p");

    heatLossElement.textContent =
        `${heatLossShare}% of modeled heat-loss opportunity`;

    tooltip.appendChild(
        heatLossElement
    );
}

// =====================================================
// [18.9.8]
// Displays available renovation opportunities.
//
// The interaction engine renders the opportunities but does
// not determine or calculate them.
// =====================================================

if (
    renovationOpportunities.length > 0
) {

    const opportunitiesHeading =
        document.createElement("h4");

    opportunitiesHeading.textContent =
        "Renovation opportunities";

    tooltip.appendChild(
        opportunitiesHeading
    );

    const opportunitiesList =
        document.createElement("ul");

    renovationOpportunities.forEach(
        opportunity => {

            const opportunityItem =
                document.createElement("li");

            opportunityItem.textContent =
                opportunity;

            opportunitiesList.appendChild(
                opportunityItem
            );
        }
    );

    tooltip.appendChild(
        opportunitiesList
    );
}

                // [3.9.13]
                // Applies hover highlight styling.
                zone.style.opacity = "0.8";

                // =====================================================
// ENGINEERING PREVIEW VISUALIZATION
// =====================================================

// [5.5.1]
// Applies contextual engineering preview states.
applyEngineeringPreview(
    zoneKey
);
            }

            
        );

        // [3.9.14]
        // Removes hover styling on mouse leave.
        zone.addEventListener(
            "mouseleave",
            () => {

                // [3.9.15]
                // Restores original opacity.
                zone.style.opacity = "1";

                // [5.5.7]
// Clears contextual engineering previews safely.
renderInstalledSystems();

// [6.4.14]
// Persists updated engineering state.
saveEngineeringState(
    energyState
);
            }
        );

        // ================================
        // CLICK INTERACTION
        // ================================

        // [3.9.16]
        // Activates scalable click interaction system.
        zone.addEventListener(
            "click",
            () => {

                // =====================================================
        // [15.1.7]
        // Hides first-use touch guidance.
        // =====================================================

        if (touchGuidance) {

            touchGuidance.classList.add(
                "hidden"
            );

        }

                openSystemSelectionPanel(
                     zoneKey
                );

            

                // [3.9.25]
                // Outputs scalable debugging trace.
                console.log(
                    "Updated Energy State:",
                    energyState
                );

                const wrapper =
    document.querySelector(
        ".interactive-house-wrapper"
    );

if (wrapper) {

    wrapper.classList.add(
        "active"
    );

const configurationPanel =
    document.getElementById(
        "configuration-panel"
    );

if (configurationPanel) {

    configurationPanel.classList.add(
        "active"
    );
}
}
            }
        );
    });
}

// [5.5.2]
// Creates contextual engineering preview visualization.
function applyEngineeringPreview(
    zoneKey
) {

    // [5.5.3]
    // Retrieves all SVG interaction zones.
    const roofZone =
        document.querySelector(
            '[data-zone="roof"]'
        );

    const wallZone =
        document.querySelector(
            '[data-zone="walls"]'
        );

    const windowZone =
        document.querySelector(
            '[data-zone="windows"]'
        );

    // =====================================================
    // ROOF PREVIEW INTELLIGENCE
    // =====================================================

    // [5.5.4]
    // Highlights related building envelope systems.
    if (zoneKey === "roof") {

        [
            wallZone,
            windowZone
        ].forEach(zone => {

            if (!zone) return;

            zone.style.filter =
                "drop-shadow(0 0 8px rgba(0,180,255,0.55))";
        });
    }

    // =====================================================
    // WALL PREVIEW INTELLIGENCE
    // =====================================================

    // [5.5.5]
    // Highlights thermal relationship systems.
    if (zoneKey === "walls") {

        [
            roofZone,
            windowZone
        ].forEach(zone => {

            if (!zone) return;

            zone.style.filter =
                "drop-shadow(0 0 8px rgba(0,255,180,0.45))";
        });
    }

    // =====================================================
    // WINDOW PREVIEW INTELLIGENCE
    // =====================================================

    // [5.5.6]
    // Highlights envelope optimization systems.
    if (zoneKey === "windows") {

        [
            roofZone,
            wallZone
        ].forEach(zone => {

            if (!zone) return;

            zone.style.filter =
                "drop-shadow(0 0 8px rgba(255,255,255,0.55))";
        });
    }
}

